# Site settings
title: Wayne's github.io site
email: leiwei.ok@gmail.com
description: >
  My personal github.io web site: blog, articles, ...
baseurl: ""

# TEMPORARY before asset/ images are uploaded
# url: "http://localhost:4000"
url: "http://gegete002536.github.io"


github_username:  gegete002536


# Build settings
markdown: kramdown

# highlighter: pygments

paginate: 2 # <- turn on pagination with two posts per page

# Build settings
theme: minima
permalink: /:year/:month/:day/:title:output_ext
plugins:
    - jekyll-paginate
    - jekyll-category-pages
